version: "3.3"

services:
    mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
            - ./db:/data/db:rw
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=pass
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
        depends_on:
            - mongo
    express:
        command: npm run dev
        build:
            context: express
            dockerfile: Dockerfile.dev
        volumes:
            - ./express:/app
            - /app/node_modules
            - ./.vscode:/app/.vscode
        ports:
            - 8000:8000
        env_file:
            - ./express/.env
        environment:
            - PORT=8000
            - ORIGIN=http://localhost:5173,http://localhost:8000,http://localhost:80,http://localhost
            - DATABASE_URL=mongodb://root:example@mongo:27017/?retryWrites=true&w=majority
            - JWT_SECRET=randomsecrethere
            - AUTO_EMPTY_TMP=true
            - RTMP_URL=rtmp://nginx:1935
            # set s3 storage envinment vars or via .env file
            # - BUCKET_NAME=
            # - BUCKET_ENDPOINT=
            # - BUCKET_REGION=
            # - BUCKET_ACCESS_KEY_ID=
            # - BUCKET_SECRET_ACCESS_KEY=
        depends_on:
            - mongo
    client:
        command: npm run dev
        build:
            context: client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
            - ./.vscode:/app/.vscode
        ports:
            - 5173:5173
        tty: true
    nginx:
        command: nginx -g 'daemon off;'
        build:
            context: nginx_conf
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        volumes:
            - ./nginx_conf:/etc/nginx
        depends_on:
            - express
            - client
