version: "3.3"

services:
    mongo:
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        volumes:
            - ./db:/data/db:rw
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=example
            - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongo:27017/
        depends_on:
            - mongo
    localstack:
        image: localstack/localstack:latest
        container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
        ports:
            - "127.0.0.1:4566:4566" # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559" # external services port range
        environment:
            # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
            - DEBUG=${DEBUG:-0}
            - SERVICES=s3
            - DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
    express:
        command: npm run dev
        build:
            context: express
            dockerfile: Dockerfile.dev
        volumes:
            - ./express:/app
            - /app/node_modules
        ports:
            - 8000:8000
        environment:
            - PORT=8000
            - ORIGIN=http://localhost:5173,http://localhost:8000,http://localhost:8000,http://localhost
            - DATABASE_URL=mongodb://root:example@mongo:27017/?retryWrites=true&w=majority
            - JWT_SECRET=randomsecrethere
            - BUCKET_NAME=radiobucket
            - BUCKET_ENDPOINT=http://localstack:4566
            - BUCKET_REGION=us-east-1
            - BUCKET_ACCESS_KEY_ID=test
            - BUCKET_SECRET_ACCESS_KEY=test
        depends_on:
            - mongo
            - localstack
    client:
        command: npm run dev
        build:
            context: client
            dockerfile: Dockerfile.dev
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - 5173:5173
        tty: true
    nginx:
        command: nginx -g 'daemon off;'
        build:
            context: nginx_conf
            dockerfile: Dockerfile.dev
        ports:
            - 80:80
        volumes:
            - ./nginx_conf:/etc/nginx
        depends_on:
            - express
            - client
