# fly.toml app configuration file generated for animeyubi-music on 2024-09-06T22:51:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'animeyubi-music'
primary_region = 'hkg'

[build]

[build.args]
  SCHEME="http"
  DOMAIN="music.animeyubi.com"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
