# fly.toml app configuration file generated for anime-ost-radio on 2023-07-31T19:46:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anime-ost-radio"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
