name: 'deploy'

on:
  push:
    branches:
      - rtmp-streaming

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@${{ secrets.IP_ADDRESS }}:22/radio-app'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
